# This workflow builds and deploys a Jekyll site to GitHub Pages using GitHub Actions

name: Deploy Jekyll site to Pages

on:
  # Trigger the workflow when there are changes pushed to the 'main' branch
  push:
    branches: ["main"]

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Limit concurrency so only one deployment runs at a time
# Do not cancel in-progress jobs to allow deployments to finish
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job for Jekyll site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v4
        with:
          ruby-version: '3.1'  # Ensure this matches the Ruby version you are using
          bundler-cache: true   # Caches gems to speed up future builds
          cache-version: 0      # Increment this number to force re-download of gems if needed

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production  # Ensures the site is built in production mode

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Directory where Jekyll outputs the built site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Add the custom domain (ensure this matches your domain setup in the CNAME file)
          custom-domain: unattributed.blog
